name: sync git to s3

on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Create $(date +'%Y-%m-%dT%H:%M:%S') zip
      run: zip -r $(date +'%Y-%m-%dT%H:%M:%S').zip . --exclude '.git*/*' --exclude '.github*/*'
    - uses: jakejarvis/s3-sync-action@v0.3.1

      with:
        args: --follow-symlinks --exclude '*' --include '*.zip'

    - name: Display the required info.
      run: |
        echo "Github Ref:$GITHUB_REF_NAME"
        echo "Github Repo:$GITHUB_REPOSITORY"
        echo "builddate=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
        echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_OUTPUT
